### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by DaveB91** [jakebailey/tikfirehol#1]
Hi Jake,

This looks really useful, but how do I use it? Haha

Cheers

**Comment by DaveB91** [comment]
I see it's a docker image, I must've missed that part. Closing.

**Comment by jakebailey** [comment]
Yeah, you just spin it up (behind a proxy if you need HTTPS). I haven't used it since I created it, however; the firehol lists often contain "unroutable" addresses, which include local IPs, which makes it more difficult than I thought to just blindly import and use. I'd like to figure it out if I have the time, but after I accidentally blocked my own traffic and tried to work out something on the server side (to remove addresses that shouldn't be blocked), I didn't find anything clean and moved on to other stuff.
